### ISSUE TITLE
Only splashscreen

### ISSUE THREAD

**Issue by fabulous-fab14** [unimonkiez/react-cordova-boilerplate#4] opened 2015-11-30 00:32 UTC
Hi!
I cloned your repo and built an android app, everthing worked fine no errors.
But when I run your app on my device it only displays the splashscreen, forever...

Is there an issue, that you are aware of?
Do I have to do anything besides the normal building process with cordova?

Here is my stackoverflow question: http://stackoverflow.com/questions/33989921/cordova-android-reactjs/33990239#33990239

**Comment by unimonkiez** [comment] 2015-11-30 09:30
Any chance you are running it with node version 5 using the command `./platforms/android/cordova/run`?

**Comment by JeffOwOSun** [comment] 2015-12-06 04:37
Here's how I managed to solve the issue:

```javascript
//webpack.config.js
...

loaders: [{
    test: /\.jsx?$/,
    loaders: ['babel'] , //remove 'react-hot'
    exclude: /node_modules/
  }, {

...

entry: [
    //'webpack-dev-server/client?', comment these two entries out
    //'webpack/hot/only-dev-server',
    './src/entry-points/Client.jsx'],

...
```

Basically what caused the problem is that when the react-hot-reloader is on, the compiled js will initiate a socket towards the `localhost`. On your computer this is fine as long as you run the webpack dev server using `npm start`. However what cordova does is simply opening up the index.html and feed it to the webview for display, nothing more than double-clicking on the `index.html` on your hard disk, and the websocket initiator will throw an error at an early stage of bundle.js evaluation, ceasing further execusion.

**Comment by unimonkiez** [comment] 2015-12-06 09:13
@JeffOwOSun I'm aware of this error but it's not something you want to comment out (because you lose hot model replacement in the process).
This might be a suitable replacement.

```javascript
entry: ['./src/entry-points/Client.jsx'].concat(
    __CORDOVA__ ? [] : [
        'webpack-dev-server/client?',
        'webpack/hot/only-dev-server'
    ])
```

And soon will be fixed.

**Comment by unimonkiez** [comment] 2015-12-06 09:17
@fabulous-fab14 About your error, it seems like a javascript error.
Could be caused by build step gone wrong.

Most common thing I came across yesterday was that `hooks/build.sh` wasn't running because it lacked permissions, I ran `chmod +x ./hook/build.sh` and it was fixed.

But to help you with this problem I got to see the build log (`cordova run android`'s log)

**Comment by fabulous-fab14** [comment] 2015-12-07 16:45
Hi!
it appeared to be like @JeffOwOSun said with the hot loader. I managed to solve my issue and my project is running on android now! As soon as I have more spare time I will be writing a tutorial about my experience with ReactJS + cordova.
Thanks for your help!

**Closed** 2015-12-11 19:31 UTC
Labels: bug, confirmed, help wanted
