### ISSUE TITLE
clean install, constant errors in the console, but app works 

### ISSUE THREAD

**Issue by brainlid** [unimonkiez/react-cordova-boilerplate#5] opened 2015-12-05 03:23 UTC
After a clean download of the repo, npm install and npm start... it "works" correctly but there are continual errors in the console.

```
GET http://localhost/info?t=1449285338378 net::ERR_CONNECTION_REFUSED
[WDS] Disconnected!
```

The URL being used in the failed GET is "localhost" but missing the port. And nothing is listening for that request. I can't figure out where the issue was coming from.

**Comment by unimonkiez** [comment] 2015-12-06 09:35
Thanks for reporting, did came across it.
will be fixed on next milestone.
For the meanwhile you can fix it on your own project, check out the comments on #4

**Comment by unimonkiez** [comment] 2015-12-11 18:02
Duplicate of #4

**Closed by unimonkiez** 2015-12-11 18:02 UTC
Labels: duplicate
